name: "🍿 Demo"
on: 
  workflow_dispatch:   

permissions:
  contents: write
  pull-requests: none 
  issues: write
  packages: none

jobs:
  security-scoring:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: OpenSSF Scorecard Monitor
        # feat/add-new-visualization-tool includes the non-released changes for the new visualization tool (v2.0.0-beta4)
        uses: UlisesGascon/openssf-scorecard-monitor@2.0.0-beta6
        id: openssf-scorecard-monitor
        with:
          scope: demo/scope.json
          database: demo/database.json
          report: demo/openssf-report.md
          auto-commit: true
          auto-push: true
          generate-issue: true
          issue-title: "[Demo] OpenSSF Scorecard Report Updated!"
          issue-assignees: 'UlisesGascon'
          issue-labels: 'demo,wontfix'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-request-in-parallel: 10
          report-tags-enabled: true
          discovery-enabled: true
          discovery-orgs: 'elastic,psf'
      - name: Print the scores
        run: |
          echo '${{ steps.openssf-scorecard-monitor.outputs.scores }}'  
